name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login 
    uses: docker/login-action@v2
    with:
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Docker Login 
    run: docker build . --file Dockerfile --tag cptr9/fastdydb:1.0

    - name: Push Docker Image
     run: docker push cptr9/fastdydb:1.0
